name: tests

on: [push, pull_request]

jobs:
  test:
  
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install package dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          pip install -U pytest
          pip install -U pytest-cov coverage-badge

      - name: Run tests with pytest
        run: |
          python -m pytest --cov

      - name: Update coverage badge
        if: ${{ matrix.python == '3.10' && matrix.os == 'ubuntu-latest' }}
        continue-on-error: true
        run: |
          coverage-badge -o tests/badge.svg -f
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/badge.svg
          git commit --author="Prerit Das <preritdas@gmail.com>" -m "Coverage badge updated after tests."
          git push
