name: tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Install test dependencies
        run: pip install -U pytest

      - name: Run tests with pytest
        run: |
          python -m pytest
