name: pypi deployment


on:
  push:
    paths:
      - setup.py
  workflow_dispatch:


jobs:
  test:
  
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install package dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          pip install -r tests/requirements.txt

      - name: Run tests with pytest
        run: |
          python -m pytest


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U pip build setuptools wheel twine

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
